### ISSUE TITLE
cifar100.train.npz - Training set of CIFAR100

### ISSUE THREAD

**Issue by sumorday** [basiclab/GNGAN-PyTorch#6]
Hi, do you have this file link? cifar100.train.npz
because it will download automatically. 
Thank you!

**Comment by w86763777** [comment]
We did not test our method on CIFAR100, so no FID statistics for CIFAR100 are available for download.

**Comment by sumorday** [comment]
Thank you. 謝謝您每一次都快速回復我！祝您萬事順心如意！you are the best！！
